name: Doxygen

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - name: Install Doxygen and Xsltproc
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen
          sudo apt-get install xsltproc
      - uses: actions/checkout@v5

      - name: Generate docs
        run: doxygen Doxyfile

      - name: Generate keywords.txt
        run: |
          xsltproc doxygen2keywords.xsl docs/xml/index.xml >keywords.txt
          echo "-----------------------------------------------------------"
          cat keywords.txt
          echo "-----------------------------------------------------------"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-pages
          FOLDER: docs/html
          
